# Generated by Django 6.0.1 on 2026-01-08 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_html', models.FileField(blank=True, null=True, upload_to='results/%Y/%m/%d/')),
                ('alpha_diversity_plot', models.FileField(blank=True, null=True, upload_to='results/%Y/%m/%d/')),
                ('beta_diversity_plot', models.FileField(blank=True, null=True, upload_to='results/%Y/%m/%d/')),
                ('taxonomy_plot', models.FileField(blank=True, null=True, upload_to='results/%Y/%m/%d/')),
                ('alpha_diversity_data', models.FileField(blank=True, null=True, upload_to='results/%Y/%m/%d/')),
                ('beta_diversity_data', models.FileField(blank=True, null=True, upload_to='results/%Y/%m/%d/')),
                ('taxonomy_data', models.FileField(blank=True, null=True, upload_to='results/%Y/%m/%d/')),
                ('nextflow_log', models.TextField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.analysisjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
