# Generated by Django 6.0.1 on 2026-01-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='is_test_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='data_type',
            field=models.CharField(choices=[('single-end', 'Single-end'), ('paired-end', 'Paired-end')], max_length=20),
        ),
    ]
